build:
    environment:
        php:
            version: 5.6
            ini:
                'date.timezone': 'Europe/Amsterdam'
filter:               
    paths: 
        - src/*
        - tests/*
checks:
    php: true
