language: php
php:
  - 7.0
  - 5.6
  - 5.5
# optionally set up exclutions and allowed failures in the matrix
matrix:
  allow_failures:
    - php: 7.0
before_script:
  - composer install -n
script:
  - phpunit
