language: php
php:
  - 7.0
  - 5.6
  - 5.5
# optionally set up exclutions and allowed failures in the matrix
matrix:
  allow_failures:
    - php: 7.0
install:
  - composer install --no-interaction
script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry php vendor/bin/coveralls -v
