language: php
php:
  - 7.0
  - 5.6
  - 5.5
matrix:
  allow_failures:
    - php: 7.0
# We only build pushes to master and pull requests
branches:
  only:
    - master
install:
  - composer install --no-interaction
  - mkdir -p build/logs
script:
  - phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry php vendor/bin/coveralls -v
